### ISSUE TITLE
GSVA:gsva function update 

### ISSUE THREAD

**Issue by 1014violin** [nbay13/biorunr#1]
Hi Nick, 

Just wanted to let you know that the gsva function has been updated in the latest version so when running ssgsea, it takes a ssgseaParam object. The run.ssGSEA modified function would look like this:

run.ssGSEA2 <- function(exp_mat, gene_list, method = "ssgsea", norm = F){
  gsvaPar <- GSVA::ssgseaParam(exp_mat, gene_list, normalize = norm)
  return(GSVA::gsva(gsvaPar))
}

**Comment by nbay13** [comment]
thanks for pointing this out. For now I've added your code as a new function in the package. Can you try re-installing and give it a try?

Later I will have to modify the function to run either ssGSEA or GSVA depending on the `method` argument

**Comment by 1014violin** [comment]
Hi Nick,

So sorry for the delay! I will reinstall and try it again tomorrow.

Best,
Alexzandra

**Comment by 1014violin** [comment]
It works!
